---
persistentVoluemClaim:
  enabled: true
ingress:
  enabled: true
serviceTCP:
  loadBalancerIP: '{{ load_balancer_server_ ip }}'
  type: loadBalancer
serviceUDP:
  loadBalancerIP: '{{ load_balancer_server_ ip }}'
  type: loadBalancer
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
# If using in the real world, don't use 'password' as your admin password... please
adminPassword: password